# Generated by Django 5.2.6 on 2025-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('coadmin', 'Co-Administrador'), ('jefe', 'Jefe de establo')], default='jefe', max_length=20, verbose_name='Rol del Usuario'),
        ),
    ]
