# Generated by Django 5.2.6 on 2025-10-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Módulo')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código del Módulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Módulo IoT',
                'verbose_name_plural': 'Módulos IoT',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruminant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='Código')),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('procedencia', models.CharField(blank=True, max_length=200, verbose_name='Procedencia')),
                ('padres', models.CharField(blank=True, max_length=300, verbose_name='Padres')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('categoria_reproductiva', models.CharField(blank=True, max_length=100, verbose_name='Categoría Reproductiva')),
                ('categoria_productiva', models.CharField(blank=True, max_length=100, verbose_name='Categoría Productiva')),
                ('fecha_ultimo_parto', models.DateField(blank=True, null=True, verbose_name='Fecha de Último Parto')),
                ('fecha_servicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Servicio')),
                ('fecha_esperada_parto', models.DateField(blank=True, null=True, verbose_name='Fecha Esperada de Parto')),
                ('edad', models.CharField(blank=True, max_length=50, verbose_name='Edad')),
                ('dias_produccion', models.CharField(blank=True, max_length=50, verbose_name='Días de Producción')),
                ('lactancia', models.CharField(blank=True, max_length=50, verbose_name='Lactancia')),
                ('estado_produccion', models.CharField(blank=True, choices=[('produccion', 'En Producción'), ('seca', 'Seca')], max_length=20, verbose_name='Estado de Producción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('modulo_iot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruminants.moduloiot', verbose_name='Módulo IoT Asignado')),
            ],
            options={
                'verbose_name': 'Ruminant',
                'verbose_name_plural': 'Ruminants',
                'ordering': ['nombre'],
            },
        ),
    ]
