# Generated by Django 5.2.6 on 2025-10-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruminants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('movimiento', 'Movimiento'), ('bateria', 'Batería'), ('ubicacion', 'Ubicación'), ('salud', 'Salud')], max_length=20, verbose_name='Tipo de Dato')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('unidad', models.CharField(blank=True, max_length=20, verbose_name='Unidad')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Datos RAW')),
                ('modulo_iot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruminants.moduloiot', verbose_name='Módulo IoT')),
            ],
            options={
                'verbose_name': 'Dato IoT',
                'verbose_name_plural': 'Datos IoT',
                'ordering': ['-timestamp'],
            },
        ),
    ]
