# Generated by Django 5.2.6 on 2025-10-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruminants', '0002_iotdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdata',
            name='tipo_dato',
        ),
        migrations.RemoveField(
            model_name='iotdata',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='iotdata',
            name='valor',
        ),
        migrations.AddField(
            model_name='iotdata',
            name='actividad',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel de Actividad'),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='bateria',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel de Batería (%)'),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='modulo_iot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_data', to='ruminants.moduloiot', verbose_name='Módulo IoT'),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos RAW (sin procesar)'),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
